/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0052cc",
        "on-primary": "#ffffff",
        "primary-container": "#e5f0ff",
        "on-primary-container": "#002966",
        "primary-fixed": "#e5f0ff",
        "primary-fixed-dim": "#99c2ff",
        "on-primary-fixed": "#001433",
        "on-primary-fixed-variant": "#003d99",
        "secondary": "#735c00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed65b",
        "on-secondary-container": "#745c00",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        "tertiary": "#003d99",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#001433",
        "on-tertiary-container": "#66a3ff",
        "tertiary-fixed": "#cce0ff",
        "tertiary-fixed-dim": "#66a3ff",
        "on-tertiary-fixed": "#000e24",
        "on-tertiary-fixed-variant": "#002966",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fbf9f8",
        "on-background": "#1b1c1c",
        "surface": "#ffffff",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e4e2e2",
        "on-surface-variant": "#43474f",
        "surface-dim": "#dbd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "outline": "#747781",
        "outline-variant": "#c4c6d1",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Atkinson Hyperlegible Next", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
